# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce52af7d6126072fa2e4d0d62402fca9446a6e169c0bab769491ea8b494a82d8b9854ba1776446fff00dcb8e1cadd9c3887b12687783755070ec9bd774bd9dbf

test:
  secret_key_base: fcaf9013c401fd83467c1b8e502f37be7d1c47dfbe7744b5c2eec8cef706c064cb3d4a7c62116421304f763ab6e8a8c36cf6aec0516f5ae0f43c96e8547c1a0f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
